### ISSUE TITLE
OSS License

### ISSUE THREAD

**Issue by athos** [mtharrison/wasm-raytracer#1]
Hi, there.

Thank you for sharing this interesting project!
I'm planning to develop some example web app demonstrating cooperation with WASM, and wondering whether you would mind if I would use your WASM code in my app. Do you have any specific OSS license for your codebase?

**Comment by mtharrison** [comment]
Hey, sure thing. I've added a BSD-3 license to the project now. If you have chance let me know what you work on.

**Comment by athos** [comment]
Thank you so much, @mtharrison! Yeah, I'd love to let you know it at some point.
